// Mocks generated by Mockito 5.0.16 from annotations
// in kokiku/test/restaurant_provider_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i6;

import 'package:kokiku/data/api/api_service.dart' as _i5;
import 'package:kokiku/data/model/content.dart' as _i3;
import 'package:kokiku/data/model/list.dart' as _i2;
import 'package:kokiku/data/model/search.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeRestaurantList_0 extends _i1.Fake implements _i2.RestaurantList {}

class _FakeRestaurantContent_1 extends _i1.Fake
    implements _i3.RestaurantContent {}

class _FakeSearchRestaurant_2 extends _i1.Fake implements _i4.SearchRestaurant {
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i5.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.RestaurantList> ListModel() =>
      (super.noSuchMethod(Invocation.method(#ListModel, []),
              returnValue:
                  Future<_i2.RestaurantList>.value(_FakeRestaurantList_0()))
          as _i6.Future<_i2.RestaurantList>);
  @override
  _i6.Future<_i3.RestaurantContent> ContentModel(dynamic id) =>
      (super.noSuchMethod(Invocation.method(#ContentModel, [id]),
              returnValue: Future<_i3.RestaurantContent>.value(
                  _FakeRestaurantContent_1()))
          as _i6.Future<_i3.RestaurantContent>);
  @override
  _i6.Future<_i4.SearchRestaurant> SearchModel(dynamic query) =>
      (super.noSuchMethod(Invocation.method(#SearchModel, [query]),
              returnValue:
                  Future<_i4.SearchRestaurant>.value(_FakeSearchRestaurant_2()))
          as _i6.Future<_i4.SearchRestaurant>);
  @override
  String toString() => super.toString();
}
